// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// +build !integration

package clinic

import (
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// DataFetcherMock is an autogenerated mock type for the DataDownloader type
type DataFetcherMock struct {
	mock.Mock
}

// GetClinicData provides a mock function with given logger field
func (_m *DataFetcherMock) GetClinicData(logger *zap.Logger) ([]Clinic, error) {
	ret := _m.Called(logger)

	var r0 []Clinic
	if rf, ok := ret.Get(0).(func(*zap.Logger) []Clinic); ok {
		r0 = rf(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Clinic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*zap.Logger) error); ok {
		r1 = rf(logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
